In [1]:
import torch
torch.cuda.empty_cache()


/home/s5727214/.pyenv/versions/anaconda3-2024.06-1/envs/emotalk/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
!python demo_multiplefiles.py --wav_path "/transfer/emotalk/3D-ETF/LVE_test/audio/" --result_path "/transfer/emotalk/EmoTalk_release-main/result/3d_result" --model_path "/transfer/emotalk/EmoTalk_release-main/pretrain_model/EmoTalk.pth" --device "cuda"


Loading model...
config.json: 100%|█████████████████████████| 1.53k/1.53k [00:00<00:00, 25.5MB/s]
config.json: 100%|█████████████████████████| 1.53k/1.53k [00:00<00:00, 25.5MB/s]
model.safetensors: 100%|████████████████████| 1.26G/1.26G [00:11<00:00, 114MB/s]
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo_multiplefiles.py:100: FutureWarning: You ar

In [2]:
import numpy as np

# Load the converted 3D vertices file
vertices = np.load("./result/3d_result/disgust_vertices.npy")

# Print the shape of the vertices array
print("Shape of vertices:", vertices.shape)

# Print a sample of vertices from the first frame (e.g., first 10 vertices)
print("Sample vertices:", vertices[30:50][:10])


Shape of vertices: (104, 6191, 3)
Sample vertices: [[[ 1.12536013e-01  1.53736973e+01  8.07644272e+00]
  [-1.06239999e-02  2.09284534e+01  2.84473395e+00]
  [ 2.71099806e-02  1.92934895e+01  5.43889284e+00]
  ...
  [-1.79152000e+00  7.29602098e+00  8.71479702e+00]
  [-1.89661396e+00  7.39863777e+00  8.64548111e+00]
  [-2.02000999e+00  7.52041006e+00  8.58892441e+00]]

 [[ 1.12536013e-01  1.53736973e+01  8.07644272e+00]
  [-1.06239999e-02  2.09284534e+01  2.84473395e+00]
  [ 2.71099806e-02  1.92934895e+01  5.43889284e+00]
  ...
  [-1.79152000e+00  7.29602098e+00  8.71479702e+00]
  [-1.89661396e+00  7.39863777e+00  8.64548111e+00]
  [-2.02000999e+00  7.52041006e+00  8.58892441e+00]]

 [[ 1.12536013e-01  1.53736973e+01  8.07644272e+00]
  [-1.06239999e-02  2.09284534e+01  2.84473395e+00]
  [ 2.71099806e-02  1.92934895e+01  5.43889284e+00]
  ...
  [-1.79152000e+00  7.29602098e+00  8.71479702e+00]
  [-1.89661396e+00  7.39863777e+00  8.64548111e+00]
  [-2.02000999e+00  7.52041006e+00  8.58892

In [3]:
import os#重新测试BS to 3d
#这里是ground truth文件 

#可以帮我整理一下代码，让它更整洁便捷吗？这是要测试emotalk的LVE，我之后也要用这套代码测试我改版之后的模型LVE，因为emotalk生成的是blendshape系数所以要先转换成3d坐标。以下是代码： 
# Blender 可执行文件路径
blender_exe = "/transfer/emotalk/EmoTalk_release-main/blender/blender"

# .blend 文件路径（需要包含 "face" 对象）
blend_file = "/transfer/emotalk/EmoTalk_release-main/render.blend"

# 转换脚本路径
script_path = "/transfer/emotalk/EmoTalk_release-main/blendshape_to_3d.py"

# 输入 blendshape 参数文件（例如从 HDTF 或其他数据集）
input_file = "/transfer/emotalk/3D-ETF/LVE_test/blendshape/01-01-08-02-02-02-01.npy"

# 输出 3D 顶点文件路径
output_file = "/transfer/emotalk/3D-ETF/LVE_test/3d_result/01-01-08-02-02-02-01.npy"

# 构造 Blender 命令（注意 -- 后面的参数会传给脚本）
command = f'{blender_exe} "{blend_file}" --background --python "{script_path}" -- "{input_file}" "{output_file}"'
print("Executing command:", command)
os.system(command)

Executing command: /transfer/emotalk/EmoTalk_release-main/blender/blender "/transfer/emotalk/EmoTalk_release-main/render.blend" --background --python "/transfer/emotalk/EmoTalk_release-main/blendshape_to_3d.py" -- "/transfer/emotalk/3D-ETF/LVE_test/blendshape/01-01-08-02-02-02-01.npy" "/transfer/emotalk/3D-ETF/LVE_test/3d_result/01-01-08-02-02-02-01.npy"


/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:558: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:90: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:558: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:90: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return se

Total frames: 98
Processed frame: 0
Processed frame: 10
Processed frame: 20
Processed frame: 30
Processed frame: 40
Processed frame: 50
Processed frame: 60
Processed frame: 70
Processed frame: 80
Processed frame: 90
Saved 3D vertices to: /transfer/emotalk/3D-ETF/LVE_test/3d_result/01-01-08-02-02-02-01.npy
Blender 3.4.1 (hash 55485cb379f7 built 2022-12-20 00:46:45)
Read prefs: /home/s5727214/.config/blender/3.4/config/userpref.blend
Read blend: /transfer/emotalk/EmoTalk_release-main/render.blend

Blender quit


0

In [1]:
from util_eval import visualize_frame

vertices_file = "/transfer/emotalk/3D-ETF/LVE_test/3d_result/01-01-08-02-02-02-01.npy"
frame_index = 40
visualize_frame(vertices_file,frame_index)

Vertices shape: (98, 6191, 3)


# ground truth动画可视化

In [1]:

import numpy as np
import trimesh
import pyrender
import time

# 加载所有帧的顶点数据（例如 shape 为 (104, 5023, 3)）
vertices_all = np.load('/transfer/emotalk/3D-ETF/LVE_test/3d_result/01-01-08-02-02-02-01.npy')
print("Vertices shape:", vertices_all.shape)

# 加载面部网格的拓扑信息 (例如 faces 的 shape 为 (num_faces, 3))
faces = np.load('./result/3d_result/oldtest/faces_tri.npy')

# 创建一个初始场景，利用第一帧的数据构建网格
scene = pyrender.Scene()
frame0 = 0
tri_mesh = trimesh.Trimesh(vertices_all[frame0], faces)
mesh = pyrender.Mesh.from_trimesh(tri_mesh)
# 添加网格节点，并保留节点引用以便后续更新
mesh_node = scene.add(mesh)

# 创建 Viewer，设置 run_in_thread=True 用于后台线程渲染
viewer = pyrender.Viewer(scene, run_in_thread=True, use_raymond_lighting=True)

# 动画参数：帧数与帧间延迟
frame_count = vertices_all.shape[0]
frame_delay = 0.05  # 每帧间隔（秒）

try:
    # 循环播放动画：在 Viewer 激活时不断更新场景
    while viewer.is_active:
        for frame in range(frame_count):
            # 使用 render_lock 确保更新时不会与渲染线程冲突
            with viewer.render_lock:
                # 更新 trimesh 对象的顶点数据（注意：faces 不变）
                tri_mesh.vertices = vertices_all[frame]
                # 更新场景：移除旧节点并添加更新后的新网格
                scene.remove_node(mesh_node)
                mesh = pyrender.Mesh.from_trimesh(tri_mesh)
                mesh_node = scene.add(mesh)
            # 控制每帧的播放速度
            time.sleep(frame_delay)
            if not viewer.is_active:
                break
except KeyboardInterrupt:
    print("动画终止。")


Vertices shape: (98, 6191, 3)


In [7]:
import os#重新测试BS to 3d
#这里是预测文件
# Blender 可执行文件路径
blender_exe = "/transfer/emotalk/EmoTalk_release-main/blender/blender"

# .blend 文件路径（需要包含 "face" 对象）
blend_file = "/transfer/emotalk/EmoTalk_release-main/render.blend"

# 转换脚本路径
script_path = "/transfer/emotalk/EmoTalk_release-main/blendshape_to_3d.py"

# 输入 blendshape 参数文件（例如从 HDTF 或其他数据集）
input_file = "/transfer/emotalk/EmoTalk_release-main/result/01-01-08-02-02-02-01.npy"

# 输出 3D 顶点文件路径
output_file = "/transfer/emotalk/EmoTalk_release-main/result/3d_result/01-01-08-02-02-02-01.npy"
#ref_path
ref_path = '/transfer/emotalk/3D-ETF/LVE_test/3d_result/'
# 构造 Blender 命令（注意 -- 后面的参数会传给脚本）
command = f'{blender_exe} "{blend_file}" --background --python "{script_path}" -- "{input_file}" "{output_file}" --ref_dir "{ref_path}"'
print("Executing command:", command)
os.system(command)

Executing command: /transfer/emotalk/EmoTalk_release-main/blender/blender "/transfer/emotalk/EmoTalk_release-main/render.blend" --background --python "/transfer/emotalk/EmoTalk_release-main/blendshape_to_3d.py" -- "/transfer/emotalk/EmoTalk_release-main/result/01-01-08-02-02-02-01.npy" "/transfer/emotalk/EmoTalk_release-main/result/3d_result/01-01-08-02-02-02-01.npy" --ref_dir "/transfer/emotalk/3D-ETF/LVE_test/3d_result/"
Blender 3.4.1 (hash 55485cb379f7 built 2022-12-20 00:46:45)
Read prefs: /home/s5727214/.config/blender/3.4/config/userpref.blend
Read blend: /transfer/emotalk/EmoTalk_release-main/render.blend
Error: Python: Traceback (most recent call last):
  File "/transfer/emotalk/EmoTalk_release-main/blendshape_to_3d.py", line 145, in <module>
    convert_blendshapes_to_vertices(input_path, output_path, obj_name="face", 
  File "/transfer/emotalk/EmoTalk_release-main/blendshape_to_3d.py", line 48, in convert_blendshapes_to_vertices
    raise ValueError("ground truth 数据的帧数与输入的 bl

/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:558: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:90: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:558: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:90: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return se

0

In [4]:
import numpy as np#这里得到了变化的3d顶点

# Load the converted 3D vertices file
vertices = np.load("./result/3d_result/01-01-08-02-02-02-01_vertices.npy")

# Print the shape of the vertices array
print("Shape of vertices:", vertices.shape)

# Print a sample of vertices from the first frame (e.g., first 10 vertices)
print("Sample vertices:", vertices[30:50][:10])

Shape of vertices: (99, 6191, 3)
Sample vertices: [[[ 5.78925796e-02  1.49702454e+01  8.22641373e+00]
  [-1.06215933e-02  2.09285145e+01  2.84471130e+00]
  [ 2.56885346e-02  1.92496948e+01  5.45447254e+00]
  ...
  [-1.83473289e+00  7.56962919e+00  8.79190350e+00]
  [-1.92135179e+00  7.68912172e+00  8.75141907e+00]
  [-2.03029823e+00  7.82474613e+00  8.73655891e+00]]

 [[ 5.97812943e-02  1.49805374e+01  8.22238731e+00]
  [-1.06216669e-02  2.09285107e+01  2.84471202e+00]
  [ 2.57376451e-02  1.92509518e+01  5.45400953e+00]
  ...
  [-1.82709157e+00  7.54635620e+00  8.78944874e+00]
  [-1.91484880e+00  7.66545105e+00  8.74760246e+00]
  [-2.02458692e+00  7.80088758e+00  8.73060036e+00]]

 [[ 6.03760444e-02  1.49854431e+01  8.22076321e+00]
  [-1.06216911e-02  2.09285107e+01  2.84471226e+00]
  [ 2.57553384e-02  1.92515526e+01  5.45378542e+00]
  ...
  [-1.82136393e+00  7.52812719e+00  8.78547955e+00]
  [-1.90989220e+00  7.64704132e+00  8.74236679e+00]
  [-2.02012277e+00  7.78247833e+00  8.723532

In [6]:
import numpy as np#这里得到了变化的3d顶点

# Load the converted 3D vertices file
vertices = np.load("/transfer/emotalk/3D-ETF/LVE_test/3d_result/01-01-08-02-02-02-01_vertices.npy")

# Print the shape of the vertices array
print("Shape of vertices:", vertices.shape)

# Print a sample of vertices from the first frame (e.g., first 10 vertices)
print("Sample vertices:", vertices[30:50][:10])

Shape of vertices: (98, 6191, 3)
Sample vertices: [[[ 9.44325626e-02  1.53104963e+01  8.10562325e+00]
  [-1.06233684e-02  2.09284687e+01  2.84472871e+00]
  [ 2.66827941e-02  1.92848415e+01  5.44207239e+00]
  ...
  [-1.73724890e+00  7.32154369e+00  8.75105381e+00]
  [-1.84140503e+00  7.43435097e+00  8.69400597e+00]
  [-1.96405625e+00  7.56529093e+00  8.65244865e+00]]

 [[ 9.51271430e-02  1.53291521e+01  8.09977531e+00]
  [-1.06234318e-02  2.09284649e+01  2.84472942e+00]
  [ 2.67070327e-02  1.92865124e+01  5.44149923e+00]
  ...
  [-1.74307132e+00  7.31118345e+00  8.75495434e+00]
  [-1.84735441e+00  7.42373466e+00  8.69819832e+00]
  [-1.97016478e+00  7.55444813e+00  8.65692425e+00]]

 [[ 9.54228118e-02  1.53324776e+01  8.09863091e+00]
  [-1.06234439e-02  2.09284649e+01  2.84472942e+00]
  [ 2.67165918e-02  1.92868328e+01  5.44138765e+00]
  ...
  [-1.74613881e+00  7.31096888e+00  8.75385475e+00]
  [-1.85037363e+00  7.42323589e+00  8.69681072e+00]
  [-1.97316790e+00  7.55368900e+00  8.655265

In [ ]:
from util_eval import visualize_frame
#可视化当前帧模型
vertices_file = "./result/3d_result/01-01-08-02-02-02-01_vertices.npy"
frame_index = 50
visualize_frame(vertices_file,frame_index)

Vertices shape: (99, 6191, 3)


In [10]:
import numpy as np
np.set_printoptions(precision=10)

def compute_lve_frame(pred_vertices, gt_vertices, lip_indices, mode='max'):
    """
    计算单帧中嘴部区域的顶点误差。
    
    参数：
      pred_vertices: (N, 3) 的预测顶点数组
      gt_vertices:   (N, 3) 的真实顶点数组
      lip_indices:   一个列表或数组，包含嘴部区域顶点的索引
      mode:          'max' 取最大误差，'mean' 取平均误差
      
    返回：
      当前帧的 LVE（单位通常为毫米）
    """
    # 取出嘴部区域的顶点
    pred_lips = pred_vertices[lip_indices]
    gt_lips = gt_vertices[lip_indices]
    # 计算欧氏距离（ℓ2 范数）——每个顶点的误差
    errors = np.linalg.norm(pred_lips - gt_lips, axis=1)
    if mode == 'max':
        return np.max(errors)
    elif mode == 'mean':
        return np.mean(errors)
    else:
        raise ValueError("mode 参数必须是 'max' 或 'mean'")

def compute_average_lve(pred_all, gt_all, lip_indices, mode='max'):
    
    """
    对整个视频序列计算平均的 LVE。
    
    参数：
      pred_all: (F, N, 3) 预测顶点数组，F 为帧数
      gt_all:   (F, N, 3) 真实顶点数组
      lip_indices: 嘴部区域顶点的索引列表
      mode: 'max' 或 'mean'
      
    返回：
      整个视频序列的平均 LVE
    """
    # 取预测和 ground truth 中最小的帧数
    num_frames_pred = pred_all.shape[0]
    num_frames_gt = gt_all.shape[0]
    num_frames = min(num_frames_pred, num_frames_gt)
    
    # 确保 lip_indices 中的每个索引都小于当前帧顶点数量
    N = pred_all[0].shape[0]
    lip_indices = [i for i in lip_indices if i < N]
    
    lve_list = []
    for f in range(num_frames):
        frame_lve = compute_lve_frame(pred_all[f], gt_all[f], lip_indices, mode)
        lve_list.append(frame_lve)
    return np.mean(lve_list)

# 示例使用：

# 1. 加载预测的 3D 顶点数据和 ground truth 数据（.npy 文件）
# 这里假设文件名分别为 "predicted_vertices.npy" 和 "ground_truth_vertices.npy"
pred_vertices_all = np.load("/transfer/emotalk/EmoTalk_release-main/result/3d_result/01-01-08-02-02-02-01_vertices.npy")  # shape: (F, N, 3)
gt_vertices_all = np.load('../3D-ETF/LVE_test/3d_result/01-01-08-02-02-02-01_vertices.npy')  # shape: (F, N, 3)
print("Predicted vertices shape:", pred_vertices_all.shape)
print("Ground truth vertices shape:", gt_vertices_all.shape)

# 2. 定义嘴部区域顶点索引
# 这里你可以通过文本文件加载，或直接在代码中定义一个列表，例如：
# 假设嘴部区域的顶点索引为：
lip_indices = [9, 10, 11, 18, 25, 26, 34, 35, 36, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 120, 127, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 148, 151, 153, 155, 419, 420, 433, 434, 435, 436, 470, 485, 486, 487, 488, 489, 490, 527, 528, 529, 530, 531, 532, 537, 538, 544, 545, 549, 553, 554, 555, 560, 563, 564, 569, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 588, 589, 591, 597, 598, 599, 601, 602, 608, 609, 610, 611, 614, 637, 638, 639, 640, 641, 642, 644, 648, 693, 694, 695, 697, 751, 754, 755, 756, 757, 758, 765, 766, 767, 910, 913, 914, 929, 1093, 1095, 1096, 1097, 1110, 1126, 1127, 1128, 1129, 1131, 1155, 1156, 1157, 1158, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1182, 1231, 1232, 1236, 1237, 1380, 1381, 1388, 1463, 1464, 1465, 1487, 1645, 1646, 1647, 1660, 1661, 1662, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2110, 2111, 2164, 2236, 2255, 2256, 2257, 2260, 2263, 2264, 2265, 2443, 2444, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2465, 2466, 2467, 2468, 2469, 2470, 2471, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 2485, 2486, 2487, 2488, 2489, 2490, 2491, 2492, 2493, 2494, 2495, 2496, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2511, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2534, 2535, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2561, 2562, 2563, 2564, 2565, 2566, 2567, 2578, 2579, 2592, 2593, 2594, 2595, 2596, 2597, 2598, 2601, 2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2615, 2616, 2617, 2618, 2619, 2626, 2627, 2628, 2629, 2630, 2631, 2632, 2645, 2646, 2647, 2648, 2649, 2650, 2651, 2652, 2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2670, 2671, 2672, 2673, 2674, 2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685, 2686, 2696, 2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2820, 2821, 2822, 2922, 2923, 2924, 2925, 2926, 2927, 2928, 2929, 2930, 2931, 2932, 2933, 2934, 2935, 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943, 2944, 2945, 2946, 2947, 2948, 2949, 2950, 2951, 2952, 2953, 2954, 2955, 2956, 2957, 2958, 2959, 2960, 2961, 2962, 2963, 2964, 2965, 2966, 2967, 2968, 2969, 2970, 2971, 2972, 2973, 2974, 2975, 2976, 2977, 2978, 2979, 2980, 2981, 2982, 2983, 2984, 2985, 2986, 2987, 2988, 2989, 2990, 2991, 2992, 2993, 2996, 2997, 2998, 2999, 3000, 3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008, 3009, 3011, 3012, 3013, 3014, 3015, 3016, 3017, 3018, 3019, 3020, 3021, 3022, 3023, 3024, 3025, 3026, 3027, 3029, 3030, 3031, 3032, 3033, 3034, 3035, 3036, 3037, 3038, 3039, 3040, 3041, 3042, 3043, 3044, 3045, 3046, 3049, 3050, 3051, 3052, 3053, 3054, 3055, 3056, 3057, 3064, 3065, 3066, 3067, 3068, 3069, 3070, 3071, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3080, 3081, 3082, 3115, 3116, 3117, 3118, 3119, 3120, 3121, 3122, 3143, 3144, 3145, 3146, 3147, 3148, 3149, 3150, 3151, 3441, 3442, 3455, 3456, 3457, 3458, 3492, 3507, 3508, 3509, 3510, 3511, 3512, 3549, 3550, 3551, 3552, 3553, 3554, 3559, 3560, 3566, 3567, 3571, 3575, 3576, 3577, 3582, 3585, 3586, 3591, 3594, 3595, 3596, 3597, 3598, 3599, 3600, 3601, 3602, 3603, 3604, 3605, 3606, 3610, 3611, 3613, 3619, 3620, 3621, 3623, 3624, 3630, 3631, 3632, 3633, 3636, 3659, 3660, 3661, 3662, 3663, 3664, 3666, 3670, 3715, 3716, 3717, 3718, 3719, 3773, 3776, 3777, 3778, 3779, 3780, 3787, 3788, 3789, 3932, 3935, 3936, 3951, 4115, 4117, 4118, 4119, 4132, 4148, 4149, 4150, 4151, 4153, 4177, 4178, 4179, 4180, 4183, 4184, 4185, 4186, 4187, 4188, 4189, 4190, 4191, 4192, 4193, 4194, 4195, 4196, 4197, 4198, 4204, 4253, 4254, 4258, 4259, 4402, 4403, 4410, 4485, 4486, 4487, 4509, 4510, 4512, 4513, 4667, 4668, 4669, 4683, 4684, 4693, 4694, 4695, 4696, 4697, 4698, 4699, 4700, 4701, 4702, 4703, 4704, 4705, 4706, 4707, 4708, 4709, 4710, 4711, 4712, 4713, 4714, 4715, 4716, 4717, 4718, 4719, 4720, 4721, 4722, 4723, 4724, 4725, 4726, 4727, 4728, 4729, 4730, 4731, 4732, 4733, 4734, 4735, 4736, 4737, 4738, 4739, 4740, 4741, 4742, 4743, 4744, 4745, 4746, 4747, 4748, 4749, 4750, 4751, 4752, 4753, 4754, 4755, 4756, 4757, 4758, 4759, 4760, 4761, 4762, 4763, 4764, 4765, 4766, 4767, 4768, 4769, 4770, 4771, 4772, 4773, 4774, 4775, 4776, 4777, 4778, 4779, 4780, 4781, 4782, 4783, 4784, 4785, 4786, 4787, 4788, 4789, 4790, 4791, 4792, 4793, 4794, 4795, 4796, 4797, 4798, 4799, 4800, 4801, 4802, 4803, 4804, 4805, 4806, 4807, 4808, 4809, 4810, 4811, 4812, 4813, 4814, 4815, 4816, 4817, 4818, 4819, 4820, 4821, 4822, 4823, 4824, 4825, 4826, 4827, 4828, 4829, 4830, 4831, 4832, 4833, 4834, 4835, 4836, 4837, 4838, 4839, 4840, 4841, 4842, 4843, 4844, 4845, 4846, 4847, 4848, 4849, 4850, 4851, 4852, 4853, 4854, 4855, 4856, 4857, 4858, 4859, 4860, 4861, 4862, 4863, 4864, 4865, 4866, 4867, 4868, 4869, 4870, 4871, 4872, 4873, 4874, 4875, 4876, 4877, 4878, 4879, 4880, 4881, 4882, 4883, 4884, 4885, 4886, 4887, 4888, 4889, 4890, 4891, 4892, 4893, 4894, 4895, 4896, 4897, 4898, 4899, 4900, 4901, 4902, 4903, 4904, 4905, 4906, 4907, 4908, 4909, 4910, 4911, 4912, 4913, 4914, 4915, 4916, 4917, 4918, 4919, 4920, 4921, 4922, 4923, 4924, 4925, 4926, 4927, 4928, 4929, 4930, 4931, 4932, 4933, 4934, 4935, 4936, 4937, 4938, 4939, 4940, 4941, 4942, 4943, 4944, 4945, 4946, 4947, 4948, 4949, 4950, 4951, 4952, 4953, 4954, 4955, 4956, 4957, 4958, 4959, 4960, 4961, 4962, 4963, 4964, 4965, 4966, 4967, 4968, 4969, 4970, 4971, 4972, 4973, 4974, 4975, 4976, 4977, 4978, 4979, 4980, 4981, 4982, 4983, 4984, 4985, 4986, 4987, 4988, 4989, 4990, 4991, 4992, 4993, 4994, 4995, 4996, 4997, 4998, 4999, 5000, 5001, 5002, 5003, 5004, 5005, 5006, 5007, 5008, 5009, 5010, 5011, 5012, 5013, 5014, 5015, 5016, 5017, 5018, 5019, 5020, 5021, 5022, 5023, 5024, 5025, 5026, 5027, 5028, 5029, 5030, 5031, 5032, 5033, 5034, 5035, 5036, 5037, 5038, 5039, 5040, 5041, 5042, 5043, 5044, 5045, 5046, 5047, 5048, 5049, 5050, 5051, 5052, 5053, 5054, 5055, 5056, 5057, 5058, 5059, 5060, 5061, 5062, 5063, 5064, 5065, 5066, 5067, 5068, 5069, 5070, 5071, 5072, 5073, 5074, 5075, 5076, 5132, 5133, 5258, 5277, 5278, 5279, 5282, 5283, 5285, 5286, 5287, 5465, 5466, 5467, 5468, 5469, 5470, 5471, 5472, 5473, 5474, 5475, 5476, 5477, 5478, 5479, 5480, 5481, 5487, 5488, 5489, 5490, 5491, 5492, 5493, 5494, 5495, 5496, 5497, 5498, 5499, 5500, 5501, 5502, 5503, 5504, 5505, 5506, 5507, 5508, 5509, 5510, 5511, 5512, 5513, 5514, 5515, 5516, 5517, 5518, 5519, 5520, 5521, 5522, 5523, 5524, 5525, 5526, 5527, 5528, 5529, 5530, 5531, 5532, 5533, 5534, 5535, 5536, 5537, 5538, 5539, 5540, 5541, 5542, 5543, 5544, 5545, 5546, 5547, 5548, 5549, 5550, 5551, 5552, 5553, 5554, 5555, 5556, 5557, 5558, 5559, 5560, 5561, 5562, 5563, 5564, 5565, 5566, 5567, 5568, 5569, 5570, 5583, 5584, 5585, 5586, 5587, 5588, 5589, 5601, 5614, 5615, 5616, 5617, 5618, 5619, 5620, 5623, 5628, 5629, 5630, 5631, 5632, 5633, 5634, 5635, 5636, 5637, 5638, 5639, 5640, 5641, 5648, 5649, 5650, 5651, 5652, 5653, 5654, 5655, 5656, 5667, 5668, 5669, 5670, 5671, 5672, 5673, 5674, 5675, 5676, 5677, 5678, 5679, 5680, 5681, 5682, 5683, 5684, 5685, 5692, 5693, 5694, 5695, 5696, 5697, 5698, 5699, 5700, 5701, 5702, 5703, 5704, 5705, 5706, 5707, 5708, 5709, 5710, 5718, 5719, 5720, 5721, 5722, 5723, 5724, 5725, 5726, 5727, 5728, 5842, 5843, 5844, 5936, 5937, 5938, 5939, 5940, 5941, 5942, 5943, 5944, 5945, 5946, 5947, 5948, 5949, 5950, 5951, 5952, 5953, 5954, 5955, 5956, 5957, 5958, 5959, 5960, 5961, 5962, 5963, 5964, 5965, 5966, 5967, 5968, 5969, 5970, 5971, 5972, 5973, 5974, 5975, 5976, 5977, 5978, 5979, 5980, 5981, 5982, 5983, 5984, 5985, 5986, 5987, 5988, 5989, 5990, 5991, 5992, 5993, 5994, 5995, 5996, 5997, 5998, 5999, 6000, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 6008, 6010, 6011, 6012, 6013, 6014, 6015, 6016, 6017, 6018, 6019, 6020, 6021, 6022, 6023, 6024, 6025, 6026, 6027, 6028, 6029, 6030, 6031, 6032, 6033, 6034, 6035, 6036, 6037, 6038, 6039, 6040, 6041, 6042, 6043, 6044, 6045, 6046, 6047, 6048, 6049, 6050, 6051, 6052, 6053, 6054, 6055, 6056, 6057, 6058, 6059, 6060, 6063, 6064, 6065, 6066, 6067, 6068, 6069, 6070, 6071, 6077, 6078, 6079, 6080, 6081, 6082, 6083, 6084, 6085, 6086, 6087, 6088, 6089, 6090, 6091, 6092, 6093, 6094, 6095, 6122, 6127, 6128, 6129, 6130, 6131, 6132, 6133, 6134, 6155, 6156, 6157, 6158, 6159, 6160, 6161, 6162, 6163]  # 示例数据，请根据你的模型实际情况设置

# 3. 计算平均 LVE（使用最大误差作为每帧的指标，这里 mode='max'）
average_lve = compute_average_lve(pred_vertices_all, gt_vertices_all, lip_indices, mode='max')
print("Average Lip Vertex Error (LVE):", average_lve)


Predicted vertices shape: (99, 6191, 3)
Ground truth vertices shape: (98, 6191, 3)
Average Lip Vertex Error (LVE): 0.8890632415921512


In [ ]:
import os
import subprocess
import time

# 定义音频文件夹和结果保存路径
audio_dir = '/transfer/emotalk/3D-ETF/LVE_test/audio/'
result_path = '/transfer/emotalk/EmoTalk_release-main/result/3d_result'

# 遍历目录中所有的 .wav 文件
for file_name in os.listdir(audio_dir):
    if file_name.lower().endswith('.wav'):
        full_wav_path = os.path.join(audio_dir, file_name)
        # 构造命令：单独调用 demo.py，为每个任务设置环境变量
        command = f"python demo.py --wav_path '{full_wav_path}' --result_path '{result_path}'"
        print("Executing command:", command)
        
        # 复制当前环境变量，并添加分配内存优化设置
        env = os.environ.copy()
        env["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
        
        # 使用 subprocess.run 执行命令，并等待任务完成
        subprocess.run(command, shell=True, env=env)
        
        # 等待几秒钟，让系统有足够时间释放内存
        time.sleep(10)


Executing command: python demo.py --wav_path '/transfer/emotalk/3D-ETF/LVE_test/audio/RD_Radio1_000.wav' --result_path '/transfer/emotalk/EmoTalk_release-main/result/3d_result'


Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo.py:21: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/mai

Executing command: python demo.py --wav_path '/transfer/emotalk/3D-ETF/LVE_test/audio/WDA_BobMenendez_000.wav' --result_path '/transfer/emotalk/EmoTalk_release-main/result/3d_result'


Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo.py:21: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/mai

Executing command: python demo.py --wav_path '/transfer/emotalk/3D-ETF/LVE_test/audio/WDA_JoeManchin_000.wav' --result_path '/transfer/emotalk/EmoTalk_release-main/result/3d_result'


Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo.py:21: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/mai

Executing command: python demo.py --wav_path '/transfer/emotalk/3D-ETF/LVE_test/audio/WDA_StenyHoyer_000.wav' --result_path '/transfer/emotalk/EmoTalk_release-main/result/3d_result'


Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo.py:21: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/mai

Executing command: python demo.py --wav_path '/transfer/emotalk/3D-ETF/LVE_test/audio/WRA_BillCassidy0_000.wav' --result_path '/transfer/emotalk/EmoTalk_release-main/result/3d_result'


Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo.py:21: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/mai

Executing command: python demo.py --wav_path '/transfer/emotalk/3D-ETF/LVE_test/audio/WRA_DanSullivan_000.wav' --result_path '/transfer/emotalk/EmoTalk_release-main/result/3d_result'


Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo.py:21: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/mai

Executing command: python demo.py --wav_path '/transfer/emotalk/3D-ETF/LVE_test/audio/WRA_ErikPaulsen_002.wav' --result_path '/transfer/emotalk/EmoTalk_release-main/result/3d_result'


Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo.py:21: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/mai

Executing command: python demo.py --wav_path '/transfer/emotalk/3D-ETF/LVE_test/audio/WRA_JebHensarling2_002.wav' --result_path '/transfer/emotalk/EmoTalk_release-main/result/3d_result'


Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
import os
import torch

# 定义音频文件夹和结果保存路径
audio_dir = '/transfer/emotalk/3D-ETF/LVE_test/audio/'
result_path = '/transfer/emotalk/EmoTalk_release-main/result/3d_result'

# 遍历目录中所有的 .wav 文件
for file_name in os.listdir(audio_dir):
    if file_name.lower().endswith('.wav'):
        full_wav_path = os.path.join(audio_dir, file_name)
        # 构造命令：对每个 wav 文件单独调用 demo.py
        command = f"python demo.py --wav_path '{full_wav_path}' --result_path '{result_path}'"
        print("Executing command:", command)
        os.system(command)
        torch.cuda.empty_cache()


Executing command: python demo.py --wav_path '/transfer/emotalk/3D-ETF/LVE_test/audio/RD_Radio1_000.wav' --result_path '/transfer/emotalk/EmoTalk_release-main/result/3d_result'


Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo.py:21: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/mai

Executing command: python demo.py --wav_path '/transfer/emotalk/3D-ETF/LVE_test/audio/WDA_BobMenendez_000.wav' --result_path '/transfer/emotalk/EmoTalk_release-main/result/3d_result'


Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo.py:21: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/mai

Executing command: python demo.py --wav_path '/transfer/emotalk/3D-ETF/LVE_test/audio/WDA_JoeManchin_000.wav' --result_path '/transfer/emotalk/EmoTalk_release-main/result/3d_result'


Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo.py:21: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/mai

Executing command: python demo.py --wav_path '/transfer/emotalk/3D-ETF/LVE_test/audio/WDA_StenyHoyer_000.wav' --result_path '/transfer/emotalk/EmoTalk_release-main/result/3d_result'


Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo.py:21: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/mai

Executing command: python demo.py --wav_path '/transfer/emotalk/3D-ETF/LVE_test/audio/WRA_BillCassidy0_000.wav' --result_path '/transfer/emotalk/EmoTalk_release-main/result/3d_result'


Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo.py:21: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/mai

Executing command: python demo.py --wav_path '/transfer/emotalk/3D-ETF/LVE_test/audio/WRA_DanSullivan_000.wav' --result_path '/transfer/emotalk/EmoTalk_release-main/result/3d_result'


## ground truth to 3d data 

In [1]:
# translate ground truth to 3d data 
import os

# Blender 可执行文件路径
blender_exe = "/transfer/emotalk/EmoTalk_release-main/blender/blender"

# .blend 文件路径（需要包含 "face" 对象）
blend_file = "/transfer/emotalk/EmoTalk_release-main/render.blend"

# 转换脚本路径
script_path = "/transfer/emotalk/EmoTalk_release-main/blendshape_to_3d.py"

# 输入 blendshape 参数文件（例如从 HDTF 或其他数据集）
input_file = "/transfer/emotalk/3D-ETF/LVE_test/blendshape"

# 输出 3D 顶点文件路径
output_file = "/transfer/emotalk/3D-ETF/LVE_test/3d_result"

# 构造 Blender 命令（注意 -- 后面的参数会传给脚本）
command = f'{blender_exe} "{blend_file}" --background --python "{script_path}" -- "{input_file}" "{output_file}"'
print("Executing command:", command)
os.system(command)

Executing command: /transfer/emotalk/EmoTalk_release-main/blender/blender "/transfer/emotalk/EmoTalk_release-main/render.blend" --background --python "/transfer/emotalk/EmoTalk_release-main/blendshape_to_3d.py" -- "/transfer/emotalk/3D-ETF/LVE_test/blendshape" "/transfer/emotalk/3D-ETF/LVE_test/3d_result"


/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:558: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:90: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:558: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:90: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return se

Processing file: /transfer/emotalk/3D-ETF/LVE_test/blendshape/RD_Radio1_000.npy
Total frames: 2249
Processed frame: 0
Processed frame: 10
Processed frame: 20
Processed frame: 30
Processed frame: 40
Processed frame: 50
Processed frame: 60
Processed frame: 70
Processed frame: 80
Processed frame: 90
Processed frame: 100
Processed frame: 110
Processed frame: 120
Processed frame: 130
Processed frame: 140
Processed frame: 150
Processed frame: 160
Processed frame: 170
Processed frame: 180
Processed frame: 190
Processed frame: 200
Processed frame: 210
Processed frame: 220
Processed frame: 230
Processed frame: 240
Processed frame: 250
Processed frame: 260
Processed frame: 270
Processed frame: 280
Processed frame: 290
Processed frame: 300
Processed frame: 310
Processed frame: 320
Processed frame: 330
Processed frame: 340
Processed frame: 350
Processed frame: 360
Processed frame: 370
Processed frame: 380
Processed frame: 390
Processed frame: 400
Processed frame: 410
Processed frame: 420
Processed

0

## prediction to 3d data 

In [4]:
# translate prediction to 3d data 
import os

# Blender 可执行文件路径
blender_exe = "/transfer/emotalk/EmoTalk_release-main/blender/blender"

# .blend 文件路径（需要包含 "face" 对象）
blend_file = "/transfer/emotalk/EmoTalk_release-main/render.blend"

# 转换脚本路径
script_path = "/transfer/emotalk/EmoTalk_release-main/blendshape_to_3d.py"

# 输入 blendshape 参数文件（例如从 HDTF 或其他数据集）
input_file = "/transfer/emotalk/EmoTalk_release-main/result/blendshape"

# 输出 3D 顶点文件路径
output_file = "/transfer/emotalk/EmoTalk_release-main/result/3d_result"

# 构造 Blender 命令（注意 -- 后面的参数会传给脚本）
command = f'{blender_exe} "{blend_file}" --background --python "{script_path}" -- "{input_file}" "{output_file}"'
print("Executing command:", command)
os.system(command)

Executing command: /transfer/emotalk/EmoTalk_release-main/blender/blender "/transfer/emotalk/EmoTalk_release-main/render.blend" --background --python "/transfer/emotalk/EmoTalk_release-main/blendshape_to_3d.py" -- "/transfer/emotalk/EmoTalk_release-main/result/blendshape" "/transfer/emotalk/EmoTalk_release-main/result/3d_result"


/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:558: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:90: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:558: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/transfer/emotalk/EmoTalk_release-main/blender/3.4/python/lib/python3.10/site-packages/numpy/_core/getlimits.py:90: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return se

Processing file: /transfer/emotalk/EmoTalk_release-main/result/blendshape/RD_Radio1_000.npy
Total frames: 2250
Processed frame: 0
Processed frame: 10
Processed frame: 20
Processed frame: 30
Processed frame: 40
Processed frame: 50
Processed frame: 60
Processed frame: 70
Processed frame: 80
Processed frame: 90
Processed frame: 100
Processed frame: 110
Processed frame: 120
Processed frame: 130
Processed frame: 140
Processed frame: 150
Processed frame: 160
Processed frame: 170
Processed frame: 180
Processed frame: 190
Processed frame: 200
Processed frame: 210
Processed frame: 220
Processed frame: 230
Processed frame: 240
Processed frame: 250
Processed frame: 260
Processed frame: 270
Processed frame: 280
Processed frame: 290
Processed frame: 300
Processed frame: 310
Processed frame: 320
Processed frame: 330
Processed frame: 340
Processed frame: 350
Processed frame: 360
Processed frame: 370
Processed frame: 380
Processed frame: 390
Processed frame: 400
Processed frame: 410
Processed frame: 4

0

In [5]:
import os
import numpy as np

np.set_printoptions(precision=10)

def compute_lve_frame(pred_vertices, gt_vertices, lip_indices, mode='max'):
    """
    计算单帧中嘴部区域的顶点误差。
    
    参数：
      pred_vertices: (N, 3) 的预测顶点数组
      gt_vertices:   (N, 3) 的真实顶点数组
      lip_indices:   一个列表或数组，包含嘴部区域顶点的索引
      mode:          'max' 取最大误差，'mean' 取平均误差
      
    返回：
      当前帧的 LVE（单位通常为毫米）
    """
    # 取出嘴部区域的顶点
    pred_lips = pred_vertices[lip_indices]
    gt_lips = gt_vertices[lip_indices]
    # 计算欧氏距离（ℓ2 范数）——每个顶点的误差
    errors = np.linalg.norm(pred_lips - gt_lips, axis=1)
    if mode == 'max':
        return np.max(errors)
    elif mode == 'mean':
        return np.mean(errors)
    else:
        raise ValueError("mode 参数必须是 'max' 或 'mean'")

def compute_average_lve(pred_all, gt_all, lip_indices, mode='max'):
    """
    对整个视频序列计算平均的 LVE。
    
    参数：
      pred_all: (F, N, 3) 预测顶点数组，F 为帧数
      gt_all:   (F, N, 3) 真实顶点数组
      lip_indices: 嘴部区域顶点的索引列表
      mode: 'max' 或 'mean'
      
    返回：
      整个视频序列的平均 LVE
    """
    # 取预测和 ground truth 中较小的帧数
    num_frames_pred = pred_all.shape[0]
    num_frames_gt = gt_all.shape[0]
    num_frames = min(num_frames_pred, num_frames_gt)
    
    # 确保 lip_indices 中的每个索引都小于当前帧顶点数量
    N = pred_all[0].shape[0]
    lip_indices = [i for i in lip_indices if i < N]
    
    lve_list = []
    for f in range(num_frames):
        frame_lve = compute_lve_frame(pred_all[f], gt_all[f], lip_indices, mode)
        lve_list.append(frame_lve)
    return np.mean(lve_list)

def compute_lve_for_folders(pred_folder, gt_folder, lip_indices, mode='max'):
    """
    遍历预测文件夹中所有 .npy 文件，并与 ground truth 文件夹中同名文件对比，
    计算每个文件的平均 LVE，返回一个字典 {文件名: LVE} 。
    """
    results = {}
    for file in os.listdir(pred_folder):
        if file.lower().endswith('.npy'):
            pred_path = os.path.join(pred_folder, file)
            gt_path = os.path.join(gt_folder, file)
            if os.path.exists(gt_path):
                # 加载预测和 ground truth 顶点数据
                pred_vertices_all = np.load(pred_path)
                gt_vertices_all = np.load(gt_path)
                print(f"Processing {file}:")
                print("  Predicted vertices shape:", pred_vertices_all.shape)
                print("  Ground truth vertices shape:", gt_vertices_all.shape)
                lve = compute_average_lve(pred_vertices_all, gt_vertices_all, lip_indices, mode)
                results[file] = lve
                print(f"  LVE = {lve}\n")
            else:
                print(f"警告：在 {gt_folder} 中找不到文件 {file}")
    return results

if __name__ == "__main__":
    # 设置预测和 ground truth 数据所在文件夹路径（请根据你实际情况修改）
    pred_folder = "/transfer/emotalk/EmoTalk_release-main/result/3d_result"       # 预测数据
    gt_folder   = "/transfer/emotalk/3D-ETF/LVE_test/3d_result"            # ground truth 数据

    # 定义嘴部区域顶点索引（请根据实际模型确定，此处仅为示例，索引列表可以较长）
    lip_indices = [9, 10, 11, 18, 25, 26, 34, 35, 36, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 120, 127, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 148, 151, 153, 155, 419, 420, 433, 434, 435, 436, 470, 485, 486, 487, 488, 489, 490, 527, 528, 529, 530, 531, 532, 537, 538, 544, 545, 549, 553, 554, 555, 560, 563, 564, 569, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 588, 589, 591, 597, 598, 599, 601, 602, 608, 609, 610, 611, 614, 637, 638, 639, 640, 641, 642, 644, 648, 693, 694, 695, 697, 751, 754, 755, 756, 757, 758, 765, 766, 767, 910, 913, 914, 929, 1093, 1095, 1096, 1097, 1110, 1126, 1127, 1128, 1129, 1131, 1155, 1156, 1157, 1158, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1182, 1231, 1232, 1236, 1237, 1380, 1381, 1388, 1463, 1464, 1465, 1487, 1645, 1646, 1647, 1660, 1661, 1662, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2110, 2111, 2164, 2236, 2255, 2256, 2257, 2260, 2263, 2264, 2265, 2443, 2444, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2465, 2466, 2467, 2468, 2469, 2470, 2471, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 2485, 2486, 2487, 2488, 2489, 2490, 2491, 2492, 2493, 2494, 2495, 2496, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2511, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2534, 2535, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2561, 2562, 2563, 2564, 2565, 2566, 2567, 2578, 2579, 2592, 2593, 2594, 2595, 2596, 2597, 2598, 2601, 2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2615, 2616, 2617, 2618, 2619, 2626, 2627, 2628, 2629, 2630, 2631, 2632, 2645, 2646, 2647, 2648, 2649, 2650, 2651, 2652, 2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2670, 2671, 2672, 2673, 2674, 2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685, 2686, 2696, 2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2820, 2821, 2822, 2922, 2923, 2924, 2925, 2926, 2927, 2928, 2929, 2930, 2931, 2932, 2933, 2934, 2935, 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943, 2944, 2945, 2946, 2947, 2948, 2949, 2950, 2951, 2952, 2953, 2954, 2955, 2956, 2957, 2958, 2959, 2960, 2961, 2962, 2963, 2964, 2965, 2966, 2967, 2968, 2969, 2970, 2971, 2972, 2973, 2974, 2975, 2976, 2977, 2978, 2979, 2980, 2981, 2982, 2983, 2984, 2985, 2986, 2987, 2988, 2989, 2990, 2991, 2992, 2993, 2996, 2997, 2998, 2999, 3000, 3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008, 3009, 3011, 3012, 3013, 3014, 3015, 3016, 3017, 3018, 3019, 3020, 3021, 3022, 3023, 3024, 3025, 3026, 3027, 3029, 3030, 3031, 3032, 3033, 3034, 3035, 3036, 3037, 3038, 3039, 3040, 3041, 3042, 3043, 3044, 3045, 3046, 3049, 3050, 3051, 3052, 3053, 3054, 3055, 3056, 3057, 3064, 3065, 3066, 3067, 3068, 3069, 3070, 3071, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3080, 3081, 3082, 3115, 3116, 3117, 3118, 3119, 3120, 3121, 3122, 3143, 3144, 3145, 3146, 3147, 3148, 3149, 3150, 3151, 3441, 3442, 3455, 3456, 3457, 3458, 3492, 3507, 3508, 3509, 3510, 3511, 3512, 3549, 3550, 3551, 3552, 3553, 3554, 3559, 3560, 3566, 3567, 3571, 3575, 3576, 3577, 3582, 3585, 3586, 3591, 3594, 3595, 3596, 3597, 3598, 3599, 3600, 3601, 3602, 3603, 3604, 3605, 3606, 3610, 3611, 3613, 3619, 3620, 3621, 3623, 3624, 3630, 3631, 3632, 3633, 3636, 3659, 3660, 3661, 3662, 3663, 3664, 3666, 3670, 3715, 3716, 3717, 3718, 3719, 3773, 3776, 3777, 3778, 3779, 3780, 3787, 3788, 3789, 3932, 3935, 3936, 3951, 4115, 4117, 4118, 4119, 4132, 4148, 4149, 4150, 4151, 4153, 4177, 4178, 4179, 4180, 4183, 4184, 4185, 4186, 4187, 4188, 4189, 4190, 4191, 4192, 4193, 4194, 4195, 4196, 4197, 4198, 4204, 4253, 4254, 4258, 4259, 4402, 4403, 4410, 4485, 4486, 4487, 4509, 4510, 4512, 4513, 4667, 4668, 4669, 4683, 4684, 4693, 4694, 4695, 4696, 4697, 4698, 4699, 4700, 4701, 4702, 4703, 4704, 4705, 4706, 4707, 4708, 4709, 4710, 4711, 4712, 4713, 4714, 4715, 4716, 4717, 4718, 4719, 4720, 4721, 4722, 4723, 4724, 4725, 4726, 4727, 4728, 4729, 4730, 4731, 4732, 4733, 4734, 4735, 4736, 4737, 4738, 4739, 4740, 4741, 4742, 4743, 4744, 4745, 4746, 4747, 4748, 4749, 4750, 4751, 4752, 4753, 4754, 4755, 4756, 4757, 4758, 4759, 4760, 4761, 4762, 4763, 4764, 4765, 4766, 4767, 4768, 4769, 4770, 4771, 4772, 4773, 4774, 4775, 4776, 4777, 4778, 4779, 4780, 4781, 4782, 4783, 4784, 4785, 4786, 4787, 4788, 4789, 4790, 4791, 4792, 4793, 4794, 4795, 4796, 4797, 4798, 4799, 4800, 4801, 4802, 4803, 4804, 4805, 4806, 4807, 4808, 4809, 4810, 4811, 4812, 4813, 4814, 4815, 4816, 4817, 4818, 4819, 4820, 4821, 4822, 4823, 4824, 4825, 4826, 4827, 4828, 4829, 4830, 4831, 4832, 4833, 4834, 4835, 4836, 4837, 4838, 4839, 4840, 4841, 4842, 4843, 4844, 4845, 4846, 4847, 4848, 4849, 4850, 4851, 4852, 4853, 4854, 4855, 4856, 4857, 4858, 4859, 4860, 4861, 4862, 4863, 4864, 4865, 4866, 4867, 4868, 4869, 4870, 4871, 4872, 4873, 4874, 4875, 4876, 4877, 4878, 4879, 4880, 4881, 4882, 4883, 4884, 4885, 4886, 4887, 4888, 4889, 4890, 4891, 4892, 4893, 4894, 4895, 4896, 4897, 4898, 4899, 4900, 4901, 4902, 4903, 4904, 4905, 4906, 4907, 4908, 4909, 4910, 4911, 4912, 4913, 4914, 4915, 4916, 4917, 4918, 4919, 4920, 4921, 4922, 4923, 4924, 4925, 4926, 4927, 4928, 4929, 4930, 4931, 4932, 4933, 4934, 4935, 4936, 4937, 4938, 4939, 4940, 4941, 4942, 4943, 4944, 4945, 4946, 4947, 4948, 4949, 4950, 4951, 4952, 4953, 4954, 4955, 4956, 4957, 4958, 4959, 4960, 4961, 4962, 4963, 4964, 4965, 4966, 4967, 4968, 4969, 4970, 4971, 4972, 4973, 4974, 4975, 4976, 4977, 4978, 4979, 4980, 4981, 4982, 4983, 4984, 4985, 4986, 4987, 4988, 4989, 4990, 4991, 4992, 4993, 4994, 4995, 4996, 4997, 4998, 4999, 5000, 5001, 5002, 5003, 5004, 5005, 5006, 5007, 5008, 5009, 5010, 5011, 5012, 5013, 5014, 5015, 5016, 5017, 5018, 5019, 5020, 5021, 5022, 5023, 5024, 5025, 5026, 5027, 5028, 5029, 5030, 5031, 5032, 5033, 5034, 5035, 5036, 5037, 5038, 5039, 5040, 5041, 5042, 5043, 5044, 5045, 5046, 5047, 5048, 5049, 5050, 5051, 5052, 5053, 5054, 5055, 5056, 5057, 5058, 5059, 5060, 5061, 5062, 5063, 5064, 5065, 5066, 5067, 5068, 5069, 5070, 5071, 5072, 5073, 5074, 5075, 5076, 5132, 5133, 5258, 5277, 5278, 5279, 5282, 5283, 5285, 5286, 5287, 5465, 5466, 5467, 5468, 5469, 5470, 5471, 5472, 5473, 5474, 5475, 5476, 5477, 5478, 5479, 5480, 5481, 5487, 5488, 5489, 5490, 5491, 5492, 5493, 5494, 5495, 5496, 5497, 5498, 5499, 5500, 5501, 5502, 5503, 5504, 5505, 5506, 5507, 5508, 5509, 5510, 5511, 5512, 5513, 5514, 5515, 5516, 5517, 5518, 5519, 5520, 5521, 5522, 5523, 5524, 5525, 5526, 5527, 5528, 5529, 5530, 5531, 5532, 5533, 5534, 5535, 5536, 5537, 5538, 5539, 5540, 5541, 5542, 5543, 5544, 5545, 5546, 5547, 5548, 5549, 5550, 5551, 5552, 5553, 5554, 5555, 5556, 5557, 5558, 5559, 5560, 5561, 5562, 5563, 5564, 5565, 5566, 5567, 5568, 5569, 5570, 5583, 5584, 5585, 5586, 5587, 5588, 5589, 5601, 5614, 5615, 5616, 5617, 5618, 5619, 5620, 5623, 5628, 5629, 5630, 5631, 5632, 5633, 5634, 5635, 5636, 5637, 5638, 5639, 5640, 5641, 5648, 5649, 5650, 5651, 5652, 5653, 5654, 5655, 5656, 5667, 5668, 5669, 5670, 5671, 5672, 5673, 5674, 5675, 5676, 5677, 5678, 5679, 5680, 5681, 5682, 5683, 5684, 5685, 5692, 5693, 5694, 5695, 5696, 5697, 5698, 5699, 5700, 5701, 5702, 5703, 5704, 5705, 5706, 5707, 5708, 5709, 5710, 5718, 5719, 5720, 5721, 5722, 5723, 5724, 5725, 5726, 5727, 5728, 5842, 5843, 5844, 5936, 5937, 5938, 5939, 5940, 5941, 5942, 5943, 5944, 5945, 5946, 5947, 5948, 5949, 5950, 5951, 5952, 5953, 5954, 5955, 5956, 5957, 5958, 5959, 5960, 5961, 5962, 5963, 5964, 5965, 5966, 5967, 5968, 5969, 5970, 5971, 5972, 5973, 5974, 5975, 5976, 5977, 5978, 5979, 5980, 5981, 5982, 5983, 5984, 5985, 5986, 5987, 5988, 5989, 5990, 5991, 5992, 5993, 5994, 5995, 5996, 5997, 5998, 5999, 6000, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 6008, 6010, 6011, 6012, 6013, 6014, 6015, 6016, 6017, 6018, 6019, 6020, 6021, 6022, 6023, 6024, 6025, 6026, 6027, 6028, 6029, 6030, 6031, 6032, 6033, 6034, 6035, 6036, 6037, 6038, 6039, 6040, 6041, 6042, 6043, 6044, 6045, 6046, 6047, 6048, 6049, 6050, 6051, 6052, 6053, 6054, 6055, 6056, 6057, 6058, 6059, 6060, 6063, 6064, 6065, 6066, 6067, 6068, 6069, 6070, 6071, 6077, 6078, 6079, 6080, 6081, 6082, 6083, 6084, 6085, 6086, 6087, 6088, 6089, 6090, 6091, 6092, 6093, 6094, 6095, 6122, 6127, 6128, 6129, 6130, 6131, 6132, 6133, 6134, 6155, 6156, 6157, 6158, 6159, 6160, 6161, 6162, 6163]  # 示例数据，请根据你的模型实际情况设置


    # 选择误差模式：'max' 或 'mean'
    mode = 'max'

    # 计算文件夹中所有文件的 LVE
    results = compute_lve_for_folders(pred_folder, gt_folder, lip_indices, mode)
    
    if results:
        overall_average_lve = np.mean(list(results.values()))
        print("Overall average LVE:", overall_average_lve)
    else:
        print("未找到任何匹配的文件。")


Processing RD_Radio1_000.npy:
  Predicted vertices shape: (2250, 6191, 3)
  Ground truth vertices shape: (2249, 6191, 3)
  LVE = 0.14604207682593162

Processing WRA_BillCassidy0_000.npy:
  Predicted vertices shape: (510, 6191, 3)
  Ground truth vertices shape: (510, 6191, 3)
  LVE = 0.7335353515095684

Processing WRA_ErikPaulsen_002.npy:
  Predicted vertices shape: (750, 6191, 3)
  Ground truth vertices shape: (750, 6191, 3)
  LVE = 0.1915850842800859

Processing WRA_JebHensarling2_002.npy:
  Predicted vertices shape: (2550, 6191, 3)
  Ground truth vertices shape: (2550, 6191, 3)
  LVE = 0.1621905051166502

Processing WRA_LisaMurkowski0_000.npy:
  Predicted vertices shape: (2100, 6191, 3)
  Ground truth vertices shape: (2100, 6191, 3)
  LVE = 0.16163857107816648

Processing WRA_PaulRyan0_001.npy:
  Predicted vertices shape: (1800, 6191, 3)
  Ground truth vertices shape: (1799, 6191, 3)
  LVE = 0.1736463026483978

Overall average LVE: 0.26143964857646673


In [14]:
!python demo.py --wav_path "/transfer/emotalk/EmoTalk_release-main/audio/disgust.wav" --result_path "/transfer/emotalk/EmoTalk_release-main/result/3d_result/" --model_path "/transfer/emotalk/EmoTalk_release-main/pretrain_model/EmoTalk.pth" --device "cuda"


config.json: 100%|█████████████████████████| 1.53k/1.53k [00:00<00:00, 18.2MB/s]
config.json: 100%|█████████████████████████| 1.53k/1.53k [00:00<00:00, 24.5MB/s]
model.safetensors: 100%|████████████████████| 1.26G/1.26G [00:11<00:00, 112MB/s]
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo.py:21: FutureWarning: You are using `torch.load` with `weigh

In [2]:
!python demo.py --wav_path "/transfer/emotalk/EmoTalk_release-main/audio/angry2.wav" --result_path "/transfer/emotalk/EmoTalk_release-main/result/3d_result/" --model_path "/transfer/emotalk/EmoTalk_release-main/pretrain_model/EmoTalk.pth" --device "cuda"


config.json: 100%|█████████████████████████| 1.53k/1.53k [00:00<00:00, 20.4MB/s]
config.json: 100%|█████████████████████████| 1.53k/1.53k [00:00<00:00, 16.9MB/s]
model.safetensors: 100%|████████████████████| 1.26G/1.26G [00:11<00:00, 112MB/s]
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at r-f/wav2vec-english-speech-emotion-recognition and are newly initialized: ['wav2vec2.lm_head.bias', 'wav2vec2.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/transfer/emotalk/EmoTalk_release-main/demo.py:21: FutureWarning: You are using `torch.load` with `weigh

In [4]:
!python demo_batch_levels.py --wav_path "/transfer/emotalk/Bournemouth University.wav" --result_path "/transfer/emotalk/EmoTalk_release-main/result/exp_result/" --model_path "/transfer/emotalk/EmoTalk_release-main/emotalk_finetuned_2_freezemorelayers.pth"


🧪 正在测试情绪等级 0 ...
/transfer/emotalk/EmoTalk_release-main/demo_batch_levels.py:13: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(args.model_p